theme: minima
title: manny's blog
description: Manny is a mechanical engineer and climber exploring the space between technology and creativity. He works in aerospace by day and spends his free time experimenting with code, movement, and storytelling through climbing, theater, and art.
google-site-verification: google61b023b44cd6e2de.html
